apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email:  chaitan@chaitan.live
    privateKeySecretRef:
      name: letsencrypt-prod-cluster-issuer-key
    solvers:
      - http01:
          ingress:
            class: nginx